import rclpy
from rclpy.node import Node

from tf_transformations import euler_from_quaternion
from geometry_msgs.msg import Twist
from sensor_msgs.msg import LaserScan
from tf2_msgs.msg import TFMessage
from nav_msgs.msg import Odometry, OccupancyGrid
import numpy as np


# NB: in this script two blocks of code are LLM-generated. The beginning and end of these blocks are pointed out by the comments.
# The large amount of code in this file is reused from the previous assignments, thus some naming might be misleading (e.g. Potential class)

class Potential(Node):
    def __init__(self):
        super().__init__('potential_node')
        self.map_publisher = self.create_publisher(OccupancyGrid, '/map', 10)
        self.width = 20
        self.height = 20
        self.resolution = 0.1

        # Beginning of a code block generated by ChatCPT 5.5
        self.cart_data = np.empty((0, 2))
        self.grid_width = int(self.width / self.resolution)
        self.grid_height = int(self.height / self.resolution)

        self.p_prior = 0.5
        self.p_occ = 0.1
        self.p_free = 0.8

        self.threshold_p_free = 0.7
        self.threshold_p_occ = 0.4

        self.l0 = np.log(self.p_prior / (1.0 - self.p_prior))
        self.l_occ = np.log(self.p_occ / (1.0 - self.p_occ))
        self.l_free = np.log(self.p_free / (1.0 - self.p_free))

        self.log_odds = np.full(
            (self.grid_height, self.grid_width),
            self.l0
        )
        # End of a code block generated by ChatCPT 5.5

        self.k_a = 0.8#1.6 #to be tuned manually
        self.k_r = -0.010#-0.032 #-//-
        self.ro = 3.6
        self.x = 0.0
        self.y = -3.0
        self.current_goal = 0
        self.goals = [np.array([2.0, -2.0]),
                      np.array([3.0, -1.0]),
                      np.array([5.0, -2.0]),
                      np.array([6.0, -4.0]),
                      np.array([5.0, -2.0]),
                      #np.array([6.0, -2.0]),
                      np.array([3.0, -1.0]),
                      np.array([3.0, 1.0]),
                      np.array([4.0, 1.5]),
                      np.array([0.0, 1.0]),
                      np.array([0.0, 0.0]),
                      ]

        #
        self.ranges = np.array([0])

        self.angle = 0.0
        self.subscriber_odom = self.create_subscription(
            Odometry,
            '/odom',
            self.odom_data_reader,
            10
        )
        self.subscription = self.create_subscription(
            LaserScan,
            '/scan',
            self.listener_callback,
            10
        )
        '''
        self.publisher = self.create_publisher(
            Twist,
            '/cmd_vel',
            10
        )
        '''
        time_period = 0.5
        #self.timer = self.create_timer(time_period, self.timer_callback)
        self.timer = self.create_timer(time_period, self.create_map)

        self.i = 0

# Beginning of a code block generated by ChatGPT 5.5
    def create_map(self):
        if not hasattr(self, "ranges") or not hasattr(self, "angles"):
            return

        alpha = 0.1  # obstacle thickness, meters
        beta = 0.02  # angular width, radians
        z_max = self.range_max

        origin_x = -10.0
        origin_y = -10.0

        for gy in range(self.grid_height):
            for gx in range(self.grid_width):

                # grid cell -> world coordinates
                cell_x = origin_x + (gx + 0.5) * self.resolution
                cell_y = origin_y + (gy + 0.5) * self.resolution

                # distance and bearing from robot to cell
                r = np.sqrt((cell_x - self.x) ** 2 + (cell_y - self.y) ** 2)
                phi = np.arctan2(cell_y - self.y, cell_x - self.x) - self.angle
                phi = self.normalize_angle(phi)

                # find nearest laser beam
                diffs = np.abs([self.normalize_angle(phi - a) for a in self.angles])
                k = np.argmin(diffs)

                z_k = self.ranges[k]
                theta_k = self.angles[k]

                # inverse sensor model
                if r > min(z_max, z_k + alpha / 2.0) or abs(phi - theta_k) > beta / 2.0:
                    continue

                if z_k < z_max and abs(r - z_k) < alpha / 2.0:
                    self.log_odds[gy, gx] += self.l_occ - self.l0

                elif r <= z_k:
                    self.log_odds[gy, gx] += self.l_free - self.l0

        # convert log-odds to probability
        probs = 1.0 - 1.0 / (1.0 + np.exp(self.log_odds))

        occ_grid = np.full((self.grid_height, self.grid_width), -1, dtype=np.int8)

        occ_grid[probs >= self.threshold_p_free] = 0
        occ_grid[probs <= self.threshold_p_occ] = 100

        msg = OccupancyGrid()
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.header.frame_id = "map"

        msg.info.map_load_time = self.get_clock().now().to_msg()
        msg.info.resolution = self.resolution
        msg.info.width = self.grid_width
        msg.info.height = self.grid_height

        msg.info.origin.position.x = origin_x
        msg.info.origin.position.y = origin_y
        msg.info.origin.position.z = 0.0
        msg.info.origin.orientation.w = 1.0

        msg.data = occ_grid.flatten().tolist()

        self.map_publisher.publish(msg)

# End of a code block generated by ChatGPT 5.5


    def timer_callback(self):
        msg = Twist()
        R = np.array([
            [np.cos(self.angle), np.sin(self.angle)],
            [-np.sin(self.angle), np.cos(self.angle)]
        ])
        v = R @ (np.array([self.x, self.y]) - self.goals[self.current_goal])
        v = -self.k_a * v/np.linalg.norm(v)

        for i in self.cart_data:
            denom = np.linalg.norm(i)
            if denom != 0 and denom < self.ro:
                v_rep = self.k_r * (1/denom - 1/self.ro) * (1/denom ** 2)* i/denom
                v += v_rep

        angle_to_goal = np.arctan2(v[1], v[0])

        msg.angular.z = self.normalize_angle(angle_to_goal)
        msg.linear.x = v[0]
        if np.linalg.norm(np.array([self.x, self.y]) - self.goals[self.current_goal]) < 0.8:
            msg.linear.x = 0.0
            if self.normalize_angle(self.angle) < 0.15:
                self.get_logger().info(f"Rotating")
                msg.angular.z = -1.0
                #self.goal_orientations[self.current_goal] - self.angle
            else:
                msg.angular.z = 0.0
                self.get_logger().info(f"DONE!")
                if len(self.goals)-1 > self.current_goal:
                    self.current_goal+=1
        self.publisher.publish(msg)

    def odom_data_reader(self, msg):
        self.x = msg.pose.pose.position.x
        self.y = msg.pose.pose.position.y
        q = msg.pose.pose.orientation
        _, _, self.angle = euler_from_quaternion([q.x, q.y, q.z, q.w])

    def listener_callback(self, msg):
        ranges = np.array(msg.ranges)
        idx = np.array([ranges <= msg.range_max]) * np.array([ranges >= msg.range_min])
        self.range_max = msg.range_max
        #self.ro = msg.range_max
        idx = idx.reshape(-1)
        angles = msg.angle_min + np.arange(len(ranges))*msg.angle_increment
        self.angles = angles[idx]
        self.ranges = ranges[idx]
        polar_data = np.vstack([self.ranges, self.angles]).T
        cart_data = self.np_polar2cart(polar_data)
        self.cart_data = cart_data

    # function from HW 2
    def np_polar2cart(self, np_polar):
        x = np_polar[:, 0] * np.cos(np_polar[:,1]) + 0.45 #!!! change of frame
        y = np_polar[:, 0] * np.sin(np_polar[:,1])
        np_cart = np.vstack([x, y]).T
        return np_cart

    def normalize_angle(self, angle):
        while angle > np.pi:
            angle -= 2.0 * np.pi
        while angle < -np.pi:
            angle += 2.0 * np.pi
        return angle

def main(args=None):
    rclpy.init(args=args)

    potential = Potential()

    rclpy.spin(potential)
    potential.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
